#ifndef PARSED_HPP
#define PARSED_HPP

void loadFromXML(Score& score) {

	// ------------------------------
	// Instrument List
	// ------------------------------
	score.addStaff(Instrument::FrenchHorn, "FrenchHorn-P1");
	score.addStaff(Instrument::Trumpet, "Trumpet-P2");
	score.addStaff(Instrument::Trombone, "Trombone-P3");
	score.addStaff(Instrument::Tuba, "Tuba-P4");

	// ------------------------------
	// Parts
	// ------------------------------
	// FrenchHorn-P1
	score.setStaff("FrenchHorn-P1");
	// m1
	score.addMeasure(TimeSignature(4, 4));
	score.setTempo(NoteType::_quarter, 116.0f, false);
	score.fillWithRests();
	// m2
	score.addMeasure();
	score.fillWithRests();
	// m3
	score.addMeasure();
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addDot();
	score.setDynamic(Dynamic::ff);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addTiedNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addTiedChord(NoteName::D4, Accidental::natural);
	score.addTiedChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::C4, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addChord(NoteName::F4, Accidental::sharp);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::C4, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addChord(NoteName::F4, Accidental::sharp);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::C4, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addChord(NoteName::F4, Accidental::sharp);
	// m4
	score.addMeasure();
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addDot();
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::G3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addChord(NoteName::D4, Accidental::sharp);
	// m5
	score.addMeasure();
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addDot();
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addTiedNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addTiedChord(NoteName::D4, Accidental::natural);
	score.addTiedChord(NoteName::F4, Accidental::natural);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_quarter);
	// m6
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::C4, Accidental::natural, NoteType::_eighth);
	score.addDot();
	score.addChord(NoteName::G4, Accidental::natural);
	score.addNote(NoteName::C4, Accidental::natural, NoteType::_32nd);
	score.addChord(NoteName::G4, Accidental::natural);
	score.addNote(NoteName::C4, Accidental::natural, NoteType::_32nd);
	score.addChord(NoteName::G4, Accidental::natural);
	score.addNote(NoteName::C4, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::G4, Accidental::natural);
	score.addTiedNote(NoteName::C4, Accidental::natural, NoteType::_eighth);
	score.addTiedChord(NoteName::G4, Accidental::natural);
	score.addRest(NoteType::_eighth);
	// m7
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::C4, Accidental::natural, NoteType::_eighth);
	score.addDot();
	score.addChord(NoteName::F4, Accidental::sharp);
	score.addNote(NoteName::C4, Accidental::natural, NoteType::_32nd);
	score.addChord(NoteName::F4, Accidental::sharp);
	score.addNote(NoteName::C4, Accidental::natural, NoteType::_32nd);
	score.addChord(NoteName::F4, Accidental::sharp);
	score.addNote(NoteName::C4, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addTiedNote(NoteName::C4, Accidental::natural, NoteType::_eighth);
	score.addTiedChord(NoteName::F4, Accidental::natural);
	score.addRest(NoteType::_eighth);
	// m8
	score.addMeasure(TimeSignature(6, 4));
	score.addRest(NoteType::_quarter);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::G3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_whole);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	// m9
	score.addMeasure();
	score.addTiedNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addTiedChord(NoteName::D4, Accidental::natural);
	score.addTiedChord(NoteName::F4, Accidental::natural);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_quarter);
	score.addRest(NoteType::_half);
	score.addRest(NoteType::_half);
	// m10
	score.addMeasure(TimeSignature(4, 4));
	score.setTempo(NoteType::_quarter, 98.0f, false);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.setDynamic(Dynamic::sffz);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addRest(NoteType::_eighth);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_quarter);
	score.addTiedNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	// m11
	score.addMeasure();
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_quarter);
	score.addDot();
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addChord(NoteName::G4, Accidental::sharp);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addChord(NoteName::G4, Accidental::sharp);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addChord(NoteName::G4, Accidental::sharp);
	score.addChord(NoteName::A4, Accidental::sharp);
	// m12
	score.addMeasure();
	score.addNote(NoteName::G3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addNote(NoteName::A3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	// m13
	score.addMeasure(TimeSignature(2, 2));
	score.setTempo(NoteType::_half, 100.0f, false);
	score.addNote(NoteName::A3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_quarter);
	score.addRest(NoteType::_half);
	// m14
	score.addMeasure();
	score.fillWithRests();
	// m15
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::D3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::G3, Accidental::sharp);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::G3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	// m16
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::G3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addNote(NoteName::G3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addNote(NoteName::G3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addNote(NoteName::G3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::A3, Accidental::sharp);
	// m17
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::D3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::G3, Accidental::sharp);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::G3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	// m18
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::G3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addNote(NoteName::G3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addNote(NoteName::G3, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addNote(NoteName::G3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::D3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addRest(NoteType::_quarter);
	// m19
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::D4, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::G4, Accidental::sharp);
	score.addChord(NoteName::C5, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::D4, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::G4, Accidental::natural);
	score.addChord(NoteName::B4, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addNote(NoteName::D4, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::G4, Accidental::sharp);
	score.addChord(NoteName::C5, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::C4, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addChord(NoteName::A4, Accidental::natural);
	score.addChord(NoteName::C5, Accidental::natural);
	// m20
	score.addMeasure();
	score.addTiedNote(NoteName::C4, Accidental::natural, NoteType::_half);
	score.addTiedChord(NoteName::F4, Accidental::natural);
	score.addTiedChord(NoteName::A4, Accidental::natural);
	score.addTiedChord(NoteName::C5, Accidental::natural);
	score.addTiedNote(NoteName::C4, Accidental::natural, NoteType::_eighth);
	score.addTiedChord(NoteName::F4, Accidental::natural);
	score.addTiedChord(NoteName::A4, Accidental::natural);
	score.addTiedChord(NoteName::C5, Accidental::natural);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_quarter);
	// m21
	score.addMeasure();
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::A3, Accidental::sharp);
	// m22
	score.addMeasure();
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_quarter);
	score.addDot();
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::A3, Accidental::sharp);
	// m23
	score.addMeasure();
	score.addNote(NoteName::D3, Accidental::sharp, NoteType::_half);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addNote(NoteName::G3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	// m24
	score.addMeasure();
	score.addNote(NoteName::G3, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::natural);
	// m25
	score.addMeasure();
	score.addNote(NoteName::D3, Accidental::sharp, NoteType::_half);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::D3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addNote(NoteName::D3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	score.addNote(NoteName::D3, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::sharp);
	// m26
	score.addMeasure();
	score.addNote(NoteName::A3, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::sharp);
	score.addChord(NoteName::D4, Accidental::natural);
	// m27
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::D4, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::G4, Accidental::sharp);
	score.addChord(NoteName::C5, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::D4, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::G4, Accidental::natural);
	score.addChord(NoteName::B4, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addNote(NoteName::D4, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::G4, Accidental::sharp);
	score.addChord(NoteName::C5, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::C4, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addChord(NoteName::A4, Accidental::natural);
	score.addChord(NoteName::C5, Accidental::natural);
	// m28
	score.addMeasure();
	score.addTiedNote(NoteName::C4, Accidental::natural, NoteType::_quarter);
	score.addTiedChord(NoteName::F4, Accidental::natural);
	score.addTiedChord(NoteName::A4, Accidental::natural);
	score.addTiedChord(NoteName::C5, Accidental::natural);
	score.addRest(NoteType::_quarter);
	score.addRest(NoteType::_half);

	// Trumpet-P2
	score.setStaff("Trumpet-P2");
	// m1
	score.addMeasure(TimeSignature(4, 4));
	score.setTempo(NoteType::_quarter, 116.0f, false);
	score.fillWithRests();
	// m2
	score.addMeasure();
	score.fillWithRests();
	// m3
	score.addMeasure();
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addDot();
	score.setDynamic(Dynamic::ff);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addTiedNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addTiedChord(NoteName::D5, Accidental::natural);
	score.addTiedChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::C5, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addChord(NoteName::F5, Accidental::sharp);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::C5, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addChord(NoteName::F5, Accidental::sharp);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::C5, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addChord(NoteName::F5, Accidental::sharp);
	// m4
	score.addMeasure();
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addDot();
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::G4, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addNote(NoteName::A4, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::C5, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::sharp);
	// m5
	score.addMeasure();
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addDot();
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addTiedNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addTiedChord(NoteName::D5, Accidental::natural);
	score.addTiedChord(NoteName::F5, Accidental::natural);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_quarter);
	// m6
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::G4, Accidental::natural, NoteType::_eighth);
	score.addDot();
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::G4, Accidental::natural, NoteType::_32nd);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::G4, Accidental::natural, NoteType::_32nd);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::G4, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addTiedNote(NoteName::G4, Accidental::natural, NoteType::_eighth);
	score.addTiedChord(NoteName::A4, Accidental::sharp);
	score.addTiedChord(NoteName::D5, Accidental::sharp);
	score.addRest(NoteType::_eighth);
	// m7
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::F4, Accidental::sharp, NoteType::_eighth);
	score.addDot();
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::F4, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::F4, Accidental::sharp, NoteType::_32nd);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::A4, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addTiedNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addTiedChord(NoteName::A4, Accidental::natural);
	score.addTiedChord(NoteName::D5, Accidental::sharp);
	score.addRest(NoteType::_eighth);
	// m8
	score.addMeasure(TimeSignature(6, 4));
	score.addRest(NoteType::_quarter);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addNote(NoteName::G4, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::A4, Accidental::sharp);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addNote(NoteName::G4, Accidental::sharp, NoteType::_eighth);
	score.addChord(NoteName::C5, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_whole);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addChord(NoteName::F5, Accidental::natural);
	// m9
	score.addMeasure();
	score.addTiedNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addTiedChord(NoteName::D5, Accidental::natural);
	score.addTiedChord(NoteName::F5, Accidental::natural);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_quarter);
	score.addRest(NoteType::_half);
	score.addRest(NoteType::_half);
	// m10
	score.addMeasure(TimeSignature(4, 4));
	score.setTempo(NoteType::_quarter, 98.0f, false);
	score.addNote(NoteName::D5, Accidental::natural, NoteType::_quarter);
	score.setDynamic(Dynamic::sffz);
	score.addChord(NoteName::F5, Accidental::natural);
	score.addChord(NoteName::A5, Accidental::sharp);
	score.addTiedNote(NoteName::D5, Accidental::natural, NoteType::_eighth);
	score.addTiedChord(NoteName::F5, Accidental::natural);
	score.addTiedChord(NoteName::A5, Accidental::sharp);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_half);
	// m11
	score.addMeasure();
	score.addRest(NoteType::_eighth);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_32nd);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_32nd);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_32nd);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_32nd);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::D5, Accidental::sharp, NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::F5, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::D5, Accidental::sharp, NoteType::_eighth);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::D5, Accidental::sharp, NoteType::_eighth);
	// m12
	score.addMeasure();
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::F5, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::D5, Accidental::sharp, NoteType::_eighth);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::D5, Accidental::sharp, NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::F5, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_16th);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_16th);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	// m13
	score.addMeasure(TimeSignature(2, 2));
	score.setTempo(NoteType::_half, 100.0f, false);
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_whole);
	score.setDynamic(Dynamic::ff);
	// m14
	score.addMeasure();
	score.addNote(NoteName::F5, Accidental::natural, NoteType::_whole);
	// m15
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::D5, Accidental::sharp, NoteType::_quarter);
	score.addNote(NoteName::D5, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::C5, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::A5, Accidental::sharp, NoteType::_half);
	// m16
	score.addMeasure();
	score.addTiedNote(NoteName::A5, Accidental::sharp, NoteType::_half);
	score.addNote(NoteName::F5, Accidental::natural, NoteType::_half);
	// m17
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::D5, Accidental::sharp, NoteType::_quarter);
	score.addNote(NoteName::D5, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::C5, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::A5, Accidental::sharp, NoteType::_half);
	// m18
	score.addMeasure();
	score.addTiedNote(NoteName::A5, Accidental::sharp, NoteType::_half);
	score.addNote(NoteName::F5, Accidental::natural, NoteType::_half);
	// m19
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::G4, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::C5, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::G4, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::B4, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addNote(NoteName::G4, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::C5, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::A4, Accidental::natural);
	score.addChord(NoteName::C5, Accidental::natural);
	// m20
	score.addMeasure();
	score.addTiedNote(NoteName::F4, Accidental::natural, NoteType::_half);
	score.addTiedChord(NoteName::A4, Accidental::natural);
	score.addTiedChord(NoteName::C5, Accidental::natural);
	score.addTiedNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addTiedChord(NoteName::A4, Accidental::natural);
	score.addTiedChord(NoteName::C5, Accidental::natural);
	score.addRest(NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	// m21
	score.addMeasure();
	score.addNote(NoteName::A4, Accidental::sharp, NoteType::_whole);
	// m22
	score.addMeasure();
	score.addNote(NoteName::F5, Accidental::natural, NoteType::_whole);
	// m23
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::D5, Accidental::sharp, NoteType::_quarter);
	score.addNote(NoteName::D5, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::C5, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::A5, Accidental::sharp, NoteType::_half);
	// m24
	score.addMeasure();
	score.addTiedNote(NoteName::A5, Accidental::sharp, NoteType::_half);
	score.addNote(NoteName::F5, Accidental::natural, NoteType::_half);
	// m25
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::D5, Accidental::sharp, NoteType::_quarter);
	score.addNote(NoteName::D5, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::C5, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::A5, Accidental::sharp, NoteType::_half);
	// m26
	score.addMeasure();
	score.addTiedNote(NoteName::A5, Accidental::sharp, NoteType::_half);
	score.addNote(NoteName::F5, Accidental::natural, NoteType::_half);
	// m27
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::G4, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::C5, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::G4, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::B4, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::natural);
	score.addNote(NoteName::G4, Accidental::sharp, NoteType::_quarter);
	score.addChord(NoteName::C5, Accidental::natural);
	score.addChord(NoteName::D5, Accidental::sharp);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::A4, Accidental::natural);
	score.addChord(NoteName::C5, Accidental::natural);
	// m28
	score.addMeasure();
	score.addTiedNote(NoteName::F4, Accidental::natural, NoteType::_half);
	score.addTiedChord(NoteName::A4, Accidental::natural);
	score.addTiedChord(NoteName::C5, Accidental::natural);
	score.addTiedNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addTiedChord(NoteName::A4, Accidental::natural);
	score.addTiedChord(NoteName::C5, Accidental::natural);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_quarter);

	// Trombone-P3
	score.setStaff("Trombone-P3");
	// m1
	score.addMeasure(TimeSignature(4, 4));
	score.setTempo(NoteType::_quarter, 116.0f, false);
	score.fillWithRests();
	// m2
	score.addMeasure();
	score.fillWithRests();
	// m3
	score.addMeasure();
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addDot();
	score.setDynamic(Dynamic::ff);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addTiedNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addTiedChord(NoteName::D4, Accidental::natural);
	score.addTiedChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addChord(NoteName::G4, Accidental::flat);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::A3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addChord(NoteName::G4, Accidental::flat);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addChord(NoteName::G4, Accidental::flat);
	// m4
	score.addMeasure();
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addDot();
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::G3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::A3, Accidental::natural);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addChord(NoteName::E4, Accidental::flat);
	// m5
	score.addMeasure();
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addDot();
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addTiedNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addTiedChord(NoteName::D4, Accidental::natural);
	score.addTiedChord(NoteName::F4, Accidental::natural);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_quarter);
	// m6
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::C3, Accidental::natural, NoteType::_eighth);
	score.addDot();
	score.addChord(NoteName::G3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::C3, Accidental::natural, NoteType::_32nd);
	score.addChord(NoteName::G3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::C3, Accidental::natural, NoteType::_32nd);
	score.addChord(NoteName::G3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::C3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::G3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addTiedNote(NoteName::C3, Accidental::natural, NoteType::_eighth);
	score.addTiedChord(NoteName::G3, Accidental::natural);
	score.addTiedChord(NoteName::B3, Accidental::flat);
	score.addTiedChord(NoteName::E4, Accidental::flat);
	score.addRest(NoteType::_eighth);
	// m7
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::C3, Accidental::natural, NoteType::_eighth);
	score.addDot();
	score.addChord(NoteName::G3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::C3, Accidental::natural, NoteType::_32nd);
	score.addChord(NoteName::G3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::C3, Accidental::natural, NoteType::_32nd);
	score.addChord(NoteName::G3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::A3, Accidental::natural);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addTiedNote(NoteName::F2, Accidental::natural, NoteType::_eighth);
	score.addTiedChord(NoteName::F3, Accidental::natural);
	score.addTiedChord(NoteName::A3, Accidental::natural);
	score.addTiedChord(NoteName::E4, Accidental::flat);
	score.addRest(NoteType::_eighth);
	// m8
	score.addMeasure(TimeSignature(6, 4));
	score.addRest(NoteType::_quarter);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	score.addNote(NoteName::G3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::B2, Accidental::flat, NoteType::_whole);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addChord(NoteName::F4, Accidental::natural);
	// m9
	score.addMeasure();
	score.addTiedNote(NoteName::B2, Accidental::natural, NoteType::_eighth);
	score.addTiedChord(NoteName::B3, Accidental::natural);
	score.addTiedChord(NoteName::D4, Accidental::natural);
	score.addTiedChord(NoteName::F4, Accidental::natural);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_quarter);
	score.addRest(NoteType::_half);
	score.addRest(NoteType::_half);
	// m10
	score.addMeasure(TimeSignature(4, 4));
	score.setTempo(NoteType::_quarter, 98.0f, false);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_quarter);
	score.addDot();
	score.setDynamic(Dynamic::sffz);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_quarter);
	score.addDot();
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_32nd);
	// m11
	score.addMeasure();
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::E4, Accidental::flat, NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::E4, Accidental::flat, NoteType::_eighth);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::E4, Accidental::flat, NoteType::_eighth);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addTuplet(3, NoteType::_eighth, false);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_16th);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_16th);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_16th);
	// m12
	score.addMeasure();
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::E4, Accidental::flat, NoteType::_eighth);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_eighth);
	score.addNote(NoteName::F4, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::A4, Accidental::flat, NoteType::_quarter);
	score.addTiedNote(NoteName::A4, Accidental::flat, NoteType::_eighth);
	score.addRest(NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_eighth);
	// m13
	score.addMeasure(TimeSignature(2, 2));
	score.setTempo(NoteType::_half, 100.0f, false);
	score.addTuplet(3, NoteType::_half, false);
	score.addRest(NoteType::_quarter);
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	// m14
	score.addMeasure();
	score.addTiedNote(NoteName::D3, Accidental::natural, NoteType::_eighth);
	score.addTiedChord(NoteName::F3, Accidental::natural);
	score.addTiedChord(NoteName::B3, Accidental::natural);
	score.addRest(NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	// m15
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::A3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	// m16
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::A3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::A3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addNote(NoteName::D3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	// m17
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::C3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::E3, Accidental::flat);
	score.addChord(NoteName::A3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	// m18
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::A3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_eighth);
	score.addChord(NoteName::A3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::B2, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::E3, Accidental::flat);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addNote(NoteName::B2, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::D3, Accidental::natural);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addNote(NoteName::B2, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::D3, Accidental::natural);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	// m19
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::A3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::G3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::B3, Accidental::natural);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::A3, Accidental::natural);
	score.addChord(NoteName::C4, Accidental::natural);
	// m20
	score.addMeasure();
	score.addTiedNote(NoteName::F3, Accidental::natural, NoteType::_eighth);
	score.addTiedChord(NoteName::A3, Accidental::natural);
	score.addTiedChord(NoteName::C4, Accidental::natural);
	score.addRest(NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_quarter);
	// m21
	score.addMeasure();
	score.addNote(NoteName::B2, Accidental::flat, NoteType::_half);
	score.addChord(NoteName::D3, Accidental::natural);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addNote(NoteName::A2, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::D3, Accidental::natural);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	// m22
	score.addMeasure();
	score.addNote(NoteName::A2, Accidental::natural, NoteType::_quarter);
	score.addDot();
	score.addChord(NoteName::D3, Accidental::natural);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::natural);
	score.addNote(NoteName::A2, Accidental::natural, NoteType::_eighth);
	score.addChord(NoteName::D3, Accidental::natural);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::B2, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::D3, Accidental::natural);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addNote(NoteName::B2, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::D3, Accidental::natural);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addNote(NoteName::A2, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::D3, Accidental::natural);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	// m23
	score.addMeasure();
	score.addNote(NoteName::G2, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::E3, Accidental::flat);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::G2, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::F3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::G3, Accidental::natural);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	// m24
	score.addMeasure();
	score.addNote(NoteName::G3, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::D4, Accidental::natural);
	// m25
	score.addMeasure();
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::B3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::E4, Accidental::flat);
	// m26
	score.addMeasure();
	score.addNote(NoteName::A3, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::B3, Accidental::flat);
	score.addChord(NoteName::D4, Accidental::natural);
	// m27
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::A3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::G3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::B3, Accidental::natural);
	score.addChord(NoteName::D4, Accidental::natural);
	score.addNote(NoteName::A3, Accidental::flat, NoteType::_quarter);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addChord(NoteName::E4, Accidental::flat);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_half);
	score.addChord(NoteName::A3, Accidental::natural);
	score.addChord(NoteName::C4, Accidental::natural);
	// m28
	score.addMeasure();
	score.addTiedNote(NoteName::F3, Accidental::natural, NoteType::_half);
	score.addTiedChord(NoteName::A3, Accidental::natural);
	score.addTiedChord(NoteName::C4, Accidental::natural);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::natural);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::natural);
	score.addChord(NoteName::C4, Accidental::natural);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_quarter);
	score.addChord(NoteName::A3, Accidental::natural);
	score.addChord(NoteName::C4, Accidental::natural);

	// Tuba-P4
	score.setStaff("Tuba-P4");
	// m1
	score.addMeasure(TimeSignature(4, 4));
	score.setTempo(NoteType::_quarter, 116.0f, false);
	score.fillWithRests();
	// m2
	score.addMeasure();
	score.fillWithRests();
	// m3
	score.addMeasure();
	score.fillWithRests();
	// m4
	score.addMeasure();
	score.fillWithRests();
	// m5
	score.addMeasure();
	score.fillWithRests();
	// m6
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::C2, Accidental::natural, NoteType::_half);
	score.setDynamic(Dynamic::ff);
	score.addTiedNote(NoteName::C2, Accidental::natural, NoteType::_eighth);
	score.addRest(NoteType::_eighth);
	// m7
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::C2, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::F1, Accidental::natural, NoteType::_quarter);
	score.addTiedNote(NoteName::F1, Accidental::natural, NoteType::_eighth);
	score.addRest(NoteType::_eighth);
	// m8
	score.addMeasure(TimeSignature(6, 4));
	score.addRest(NoteType::_half);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_whole);
	// m9
	score.addMeasure();
	score.addTiedNote(NoteName::B1, Accidental::natural, NoteType::_eighth);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_quarter);
	score.addRest(NoteType::_half);
	score.addRest(NoteType::_half);
	// m10
	score.addMeasure(TimeSignature(4, 4));
	score.setTempo(NoteType::_quarter, 98.0f, false);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_quarter);
	score.setDynamic(Dynamic::sffz);
	score.addTiedNote(NoteName::B1, Accidental::flat, NoteType::_eighth);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_half);
	// m11
	score.addMeasure();
	score.fillWithRests();
	// m12
	score.addMeasure();
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::E3, Accidental::flat, NoteType::_eighth);
	score.addNote(NoteName::B2, Accidental::flat, NoteType::_eighth);
	score.addNote(NoteName::F3, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::A3, Accidental::flat, NoteType::_quarter);
	score.addTiedNote(NoteName::A3, Accidental::flat, NoteType::_eighth);
	score.addRest(NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_eighth);
	// m13
	score.addMeasure(TimeSignature(2, 2));
	score.setTempo(NoteType::_half, 100.0f, false);
	score.addTuplet(3, NoteType::_half, false);
	score.addRest(NoteType::_quarter);
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_eighth);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_eighth);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_half);
	// m14
	score.addMeasure();
	score.addTiedNote(NoteName::B1, Accidental::natural, NoteType::_eighth);
	score.addRest(NoteType::_eighth);
	score.addTuplet(3, NoteType::_quarter, false);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_eighth);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_eighth);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_eighth);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_quarter);
	score.addNote(NoteName::F1, Accidental::natural, NoteType::_quarter);
	// m15
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_quarter);
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_quarter);
	// m16
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_quarter);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::B2, Accidental::flat, NoteType::_quarter);
	score.addNote(NoteName::B2, Accidental::flat, NoteType::_quarter);
	score.addNote(NoteName::B2, Accidental::flat, NoteType::_quarter);
	// m17
	score.addMeasure();
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_quarter);
	score.addRest(NoteType::_quarter);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_quarter);
	// m18
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_eighth);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_quarter);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_quarter);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_quarter);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_quarter);
	// m19
	score.addMeasure();
	score.addRest(NoteType::_half);
	score.addNote(NoteName::F1, Accidental::natural, NoteType::_eighth);
	score.setDynamic(Dynamic::sffz);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_quarter);
	// m20
	score.addMeasure();
	score.addRest(NoteType::_half);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_quarter);
	// m21
	score.addMeasure();
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_half);
	score.addNote(NoteName::A1, Accidental::natural, NoteType::_half);
	// m22
	score.addMeasure();
	score.addNote(NoteName::A1, Accidental::natural, NoteType::_quarter);
	score.addDot();
	score.addNote(NoteName::A1, Accidental::natural, NoteType::_eighth);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_quarter);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_quarter);
	score.addNote(NoteName::A1, Accidental::natural, NoteType::_quarter);
	// m23
	score.addMeasure();
	score.addNote(NoteName::G1, Accidental::natural, NoteType::_half);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::G1, Accidental::natural, NoteType::_half);
	score.addNote(NoteName::E2, Accidental::flat, NoteType::_quarter);
	// m24
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::E2, Accidental::flat, NoteType::_quarter);
	score.addNote(NoteName::D2, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::C2, Accidental::natural, NoteType::_quarter);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_quarter);
	score.addNote(NoteName::A1, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::G1, Accidental::natural, NoteType::_quarter);
	// m25
	score.addMeasure();
	score.addNote(NoteName::F1, Accidental::natural, NoteType::_half);
	score.addNote(NoteName::G1, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::A1, Accidental::natural, NoteType::_quarter);
	// m26
	score.addMeasure();
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_quarter);
	score.addNote(NoteName::A1, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::G1, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::F1, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::B1, Accidental::flat, NoteType::_quarter);
	// m27
	score.addMeasure();
	score.addNote(NoteName::F2, Accidental::natural, NoteType::_half);
	score.addTuplet(3, NoteType::_half, false);
	score.addNote(NoteName::F1, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::F1, Accidental::natural, NoteType::_quarter);
	score.addNote(NoteName::F1, Accidental::natural, NoteType::_quarter);
	// m28
	score.addMeasure();
	score.addNote(NoteName::F1, Accidental::natural, NoteType::_half);
	score.addNote(NoteName::F1, Accidental::natural, NoteType::_eighth);
	score.addRest(NoteType::_eighth);
	score.addRest(NoteType::_quarter);

}

#endif